	'sensitive_word'=>'敏感詞',
	'sensitive_word_setting'=>'敏感詞設置',
	'username_sensitive_word'=>'用戶名敏感詞',
	'post_sensitive_word'=>'發帖敏感詞',
	'username_sensitive_word_tips'=>'每個詞語之間用“,（逗號）”分隔',
	'post_sensitive_word_tips'=>'每個詞語中間用“,（逗號）”分隔。敏感詞可參考<a href="http://bbs.xiuno.com/thread-20899.htm" target="_blank">這里</a>',
	'username_contain_sensitive_word'=>'用戶名含有敏感詞：',
	'thread_contain_sensitive_word'=>'標題內容含有敏感詞：',
	'post_contain_sensitive_word'=>'帖子內容含有敏感詞：',