	'sensitive_word'=>'sensitive word',
	'sensitive_word_setting'=>'setting sensitive words',
	'username_sensitive_word'=>'sensitive word of username',
	'post_sensitive_word'=>'sensitive word of post',
	'username_sensitive_word_tips'=>'the each words split by comma',
	'post_sensitive_word_tips'=>'the each words split by comma. Reference resource <a href="http://bbs.xiuno.com/thread-20899.htm" target="_blank">here</a>',
	'username_contain_sensitive_word'=>'the user name contains a sensitive word: ',
	'thread_contain_sensitive_word'=>'subject contains a sensitive word: ',
	'post_contain_sensitive_word'=>'message contains a sensitive word: ',