	'sensitive_word'=>'敏感词',
	'sensitive_word_setting'=>'敏感词设置',
	'username_sensitive_word'=>'用户名敏感词',
	'post_sensitive_word'=>'发帖敏感词',
	'username_sensitive_word_tips'=>'每个词语之间用“,（逗号）”分隔',
	'post_sensitive_word_tips'=>'每个词语中间用“,（逗号）”分隔。敏感词可参考<a href="http://bbs.xiuno.com/thread-20899.htm" target="_blank">这里</a>',
	'username_contain_sensitive_word'=>'用户名含有敏感词：',
	'thread_contain_sensitive_word'=>'标题内容含有敏感词：',
	'post_contain_sensitive_word'=>'帖子内容含有敏感词：',